version: "3.7"
services:
    api:
        build:
            context: .
        image: php
        container_name: php
        ports:
            - "8080:8080"
        volumes:
            - ".:/var/www/html/"
        command: php -S 0.0.0.0:8080 -t public/
        links:
            - mysql
    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - mysql:/var/lib/mysql/
        environment:
            MYSQL_DATABASE: 'database'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'mysecretpassword'
            MYSQL_ROOT_PASSWORD: 'mysecretpassword'
volumes:
    mysql: null
